language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly

# Uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: 1.3
  - julia: nightly

notifications:
  email: false

addons:
  apt: # apt-get for linux
    packages:
    - libudunits2-dev

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      addons:
        apt: # apt-get for linux
          packages:
          - libudunits2-dev
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ -e 'using Pkg; Pkg.build()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
