name = "UDUnits"
uuid = "c1403bd2-e34a-5715-b454-1ca6f7e8d33a"
keywords = ["units", "netcdf", "climate and forecast conventions"]
license = "MIT"
desc = "A Julia interface for UDUnits2 for units of physical quantities"
version = "0.2.2"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
CondaBinDeps = "a9693cdc-2bc8-5703-a9cd-1da358117377"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BinDeps = "≥ 0.4.0"
julia = "1"
