name = "UDUnits"
uuid = "c1403bd2-e34a-5715-b454-1ca6f7e8d33a"
keywords = ["units", "netcdf", "climate and forecast conventions"]
license = "MIT"
desc = "A Julia interface for UDUnits2 for units of physical quantities"
version = "0.2.3"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UDUNITS_jll = "2619efb9-15dd-5c8d-95a3-19a84f6456dc"

[compat]
julia = "1"
